models:
  openai:
    enabled: true
    api_key: "sk-..."  # ← deinen echten API-Schlüssel hier eintragen oder Umgebungsvariable
  claude:
    enabled: false
    api_key: ""
  ollama:
    enabled: false
    model_name: "llama3"
